// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ReadCategoryTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void readRategory() {
    driver.get("https://adtf2020-webapp.netlify.app/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector(".au-target:nth-child(2) > .au-target:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".au-target:nth-child(2) > .au-target:nth-child(2)")).sendKeys("Écrire un livre");
    driver.findElement(By.cssSelector(".au-target:nth-child(2) > .au-target:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".au-target:nth-child(2) > .au-target:nth-child(2)")).sendKeys("Réaliser un spike de test");
    driver.findElement(By.cssSelector("label:nth-child(1) > .au-target")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector("label:nth-child(1) > .au-target"));
      dropdown.findElement(By.xpath("//option[. = 'Professionnel']")).click();
    }
    driver.findElement(By.cssSelector(".au-target:nth-child(2) > .au-target:nth-child(3)")).click();
    driver.findElement(By.cssSelector("body > .au-target > .au-target:nth-child(2)")).sendKeys("Tapisser le mur du salon");
    driver.findElement(By.cssSelector("label:nth-child(1) > .au-target")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector("label:nth-child(1) > .au-target"));
      dropdown.findElement(By.xpath("//option[. = 'Personnel']")).click();
    }
    driver.findElement(By.cssSelector("body > .au-target > .au-target:nth-child(3)")).click();
    driver.findElement(By.cssSelector("body > .au-target > .au-target:nth-child(2)")).sendKeys("Évaluer un framework de développement de test");
    driver.findElement(By.cssSelector("label:nth-child(1) > .au-target")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector("label:nth-child(1) > .au-target"));
      dropdown.findElement(By.xpath("//option[. = 'Professionnel']")).click();
    }
    driver.findElement(By.cssSelector("body > .au-target > .au-target:nth-child(3)")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("ul > .au-target:nth-child(1) > .au-target:nth-child(2)"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("ul > .au-target:nth-child(2) > .au-target:nth-child(3)"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".au-target:nth-child(3) > .au-target:nth-child(3)"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".au-target:nth-child(4) > .au-target:nth-child(3)"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.name("category_to_display")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("ul .au-target:nth-child(3)"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector("label:nth-child(6) > .au-target")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("ul > .au-target:nth-child(1) > .au-target:nth-child(3)"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("ul > .au-target:nth-child(2) > .au-target:nth-child(3)"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector("label:nth-child(7) > .au-target")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("label:nth-child(7) > .au-target"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("ul > .au-target:nth-child(1) > .au-target:nth-child(2)"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("ul > .au-target:nth-child(2) > .au-target:nth-child(3)"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".au-target:nth-child(3) > .au-target:nth-child(3)"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".au-target:nth-child(4) > .au-target:nth-child(3)"));
      assert(elements.size() > 0);
    }
  }
}
